package gr.hua.dit.ap.vmp.entities;

public enum NotificationType {
    PROFILE_APPROVED,
    PROFILE_REJECTED,
    EVENT_APPROVED,
    EVENT_REJECTED,
    NEW_REGISTRATION,
    REGISTRATION_APPROVED,
    REGISTRATION_REJECTED,
    EVENT_CANCELLED,
    NEW_REVIEW,
    COMMENT_HIDDEN,
    REGISTRATION_CANCELLED
}
